### ISSUE TITLE
Guardrail 4: Code Pointing to an Old Indicator?

### ISSUE THREAD

**Issue by MathesonSho** [Azure/GuardrailsSolutionAccelerator#168] opened 2022-09-29 21:39 UTC
**Describe the bug**
Currently cannot determine whether AppID has been installed for SSC Cloud Brokering Service Reporting. Code is searching for User account "SSC-CBS-Reporting@" + DepartmentNumber + "gc.onmicrosoft.com" but now the AppID instructions create an app registration called "SSC-CBS-Reporting-PrivateMarketplace"

**Software versions used:**
1.0.4

**Comment by igomaa** [comment] 2023-02-14 23:50
closing the  the issue as it is duplicate of #199

**Closed by igomaa** 2023-02-14 23:50 UTC
Labels: enhancement
